version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka Broker 1
  kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-1
    labels:
      - "broker.name=kafka-1"
    depends_on:
      - zookeeper
    ports:
      - "5092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1

  # Kafka Broker 2
  kafka-2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-2
    labels:
      - "broker.name=kafka-2"
    depends_on:
      - zookeeper
    ports:
      - "5093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1

  mongodb:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
      mongodb:
        condition: service_started
    command: sh -c 'sleep 10 && npm start'
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092
      - MONGODB_URI=mongodb://mongodb:27017/analytics
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    restart: on-failure

  worker:
    build: ./worker
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
      mongodb:
        condition: service_started
    command: sh -c 'sleep 15 && npm start'
    environment:
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092
      - MONGODB_URI=mongodb://mongodb:27017/analytics
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    restart: on-failure

volumes:
  mongo-data: